/*
 * SEVSEG_cfg.h
 *
 *  Created on: Oct 9, 2020
 *      Author: Shady
 */

#ifndef SEVSEG_DRIVER_SEVSEG_CFG_H_
#define SEVSEG_DRIVER_SEVSEG_CFG_H_

#define SEVSEG0_CONN COMMON_CATHOD
#define SEVSEG0_ENABLE PIN22
#define SEVSEG0_PINA PIN1
#define SEVSEG0_PINB PIN2
#define SEVSEG0_PINC PIN3
#define SEVSEG0_PIND PIN4
#define SEVSEG0_PINE PIN5
#define SEVSEG0_PINF PIN6
#define SEVSEG0_PING PIN7
#define SEVSEG0_PINDOT PIN8

#define SEVSEG1_CONN COMMON_CATHOD
#define SEVSEG1_ENABLE PIN23
#define SEVSEG1_PINA PIN1
#define SEVSEG1_PINB PIN2
#define SEVSEG1_PINC PIN3
#define SEVSEG1_PIND PIN4
#define SEVSEG1_PINE PIN5
#define SEVSEG1_PINF PIN6
#define SEVSEG1_PING PIN7
#define SEVSEG1_PINDOT PIN8

#endif /* SEVSEG_DRIVER_SEVSEG_CFG_H_ */
