/*
 * LED_cfg.h
 *
 *  Created on: Oct 3, 2020
 *      Author: Shady
 */

#ifndef LED_CFG_H_
#define LED_CFG_H_
/* 
#define LED_RED_INIT OFF
#define LED_GREEN_INIT OFF
#define LED_BLUE_INIT OFF

#define LED_RED_DIR FORWORD
#define LED_GREEN_DIR FORWORD
#define LED_BLUE_DIR FORWORD */


#define LED0_CONN FORWORD
#define LED0_PIN PIN16
#define LED0_INIT_STATE OFF

#define LED1_CONN FORWORD
#define LED1_PIN PIN17
#define LED1_INIT_STATE OFF

#define LED2_CONN FORWORD
#define LED2_PIN PIN18
#define LED2_INIT_STATE OFF

#define LED3_CONN FORWORD
#define LED3_PIN PIN19
#define LED3_INIT_STATE OFF

#define LED4_CONN FORWORD
#define LED4_PIN PIN20
#define LED4_INIT_STATE OFF

#define LED5_CONN FORWORD
#define LED5_PIN PIN21
#define LED5_INIT_STATE OFF

#define LED6_CONN FORWORD
#define LED6_PIN PIN16
#define LED6_INIT_STATE OFF

#define LED7_CONN FORWORD
#define LED7_PIN PIN16
#define LED7_INIT_STATE OFF

#define LED8_CONN FORWORD
#define LED8_PIN PIN16
#define LED8_INIT_STATE OFF

#define LED9_CONN FORWORD
#define LED9_PIN PIN16
#define LED9_INIT_STATE OFF

#define LED10_CONN FORWORD
#define LED10_PIN PIN16
#define LED10_INIT_STATE OFF

#define LED11_CONN FORWORD
#define LED11_PIN PIN17
#define LED11_INIT_STATE OFF

#define LED12_CONN FORWORD
#define LED12_PIN PIN18
#define LED12_INIT_STATE OFF

#define LED13_CONN FORWORD
#define LED13_PIN PIN16
#define LED13_INIT_STATE OFF

#define LED14_CONN FORWORD
#define LED14_PIN PIN16
#define LED14_INIT_STATE OFF

#define LED15_CONN FORWORD
#define LED15_PIN PIN16
#define LED15_INIT_STATE OFF

#define LED16_CONN FORWORD
#define LED16_PIN PIN16
#define LED16_INIT_STATE OFF

#define LED17_CONN FORWORD
#define LED17_PIN PIN16
#define LED17_INIT_STATE OFF

#define LED18_CONN FORWORD
#define LED18_PIN PIN16
#define LED18_INIT_STATE OFF

#define LED19_CONN FORWORD
#define LED19_PIN PIN16
#define LED19_INIT_STATE OFF

#define LED20_CONN FORWORD
#define LED20_PIN PIN16
#define LED20_INIT_STATE OFF

#define LED21_CONN FORWORD
#define LED21_PIN PIN17
#define LED21_INIT_STATE OFF

#define LED22_CONN FORWORD
#define LED22_PIN PIN18
#define LED22_INIT_STATE OFF

#define LED23_CONN FORWORD
#define LED23_PIN PIN16
#define LED23_INIT_STATE OFF

#define LED24_CONN FORWORD
#define LED24_PIN PIN16
#define LED24_INIT_STATE OFF

#define LED25_CONN FORWORD
#define LED25_PIN PIN16
#define LED25_INIT_STATE OFF

#define LED26_CONN FORWORD
#define LED26_PIN PIN16
#define LED26_INIT_STATE OFF

#define LED27_CONN FORWORD
#define LED27_PIN PIN16
#define LED27_INIT_STATE OFF

#define LED28_CONN FORWORD
#define LED28_PIN PIN16
#define LED28_INIT_STATE OFF

#define LED29_CONN FORWORD
#define LED29_PIN PIN16
#define LED29_INIT_STATE OFF

#define LED30_CONN FORWORD
#define LED30_PIN PIN16
#define LED30_INIT_STATE OFF

#define LED31_CONN FORWORD
#define LED31_PIN PIN16
#define LED31_INIT_STATE OFF

#endif /* LED_CFG_H_ */
