/*
 * KEYPAD_cfg.h
 *
 *  Created on: Oct 13, 2020
 *      Author: Shady
 */

#ifndef DRIVERS_KEYPAD_DRIVER_KEYPAD_CFG_H_
#define DRIVERS_KEYPAD_DRIVER_KEYPAD_CFG_H_

#define KEYPAD1_CONN PULL_UP
#define KEYPAD2_CONN PULL_UP
#define KEYPAD3_CONN PULL_UP
#define KEYPAD4_CONN PULL_UP

#define KEYPAD1_IN_PIN PIN26
#define KEYPAD2_IN_PIN PIN27
#define KEYPAD3_IN_PIN PIN28
#define KEYPAD4_IN_PIN PIN29

#define KEYPAD1_OUT_PIN PIN12
#define KEYPAD2_OUT_PIN PIN13
#define KEYPAD3_OUT_PIN PIN14
#define KEYPAD4_OUT_PIN PIN15

#endif /* DRIVERS_KEYPAD_DRIVER_KEYPAD_CFG_H_ */
