/*
 * SWITCH_cfg.h
 *
 *  Created on: Oct 4, 2020
 *      Author: Shady
 */

#ifndef SWITCH_DRIVER_SWITCH_CFG_H_
#define SWITCH_DRIVER_SWITCH_CFG_H_

#define SWITCH0_CONN PULL_UP
#define SWITCH0_PIN PIN26

#define SWITCH1_CONN PULL_UP
#define SWITCH1_PIN PIN27

#define SWITCH2_CONN PULL_UP
#define SWITCH2_PIN PIN28

#define SWITCH3_CONN PULL_UP
#define SWITCH3_PIN PIN29

#define SWITCH4_CONN PULL_UP
#define SWITCH4_PIN PIN26

#define SWITCH5_CONN PULL_UP
#define SWITCH5_PIN PIN12

#define SWITCH6_CONN PULL_UP
#define SWITCH6_PIN PIN13

#define SWITCH7_CONN PULL_UP
#define SWITCH7_PIN PIN14

#define SWITCH8_CONN PULL_UP
#define SWITCH8_PIN PIN15

#define SWITCH9_CONN PULL_UP
#define SWITCH9_PIN PIN26

#define SWITCH10_CONN PULL_UP
#define SWITCH10_PIN PIN26

#define SWITCH11_CONN PULL_UP
#define SWITCH11_PIN PIN17

#define SWITCH12_CONN PULL_UP
#define SWITCH12_PIN PIN18

#define SWITCH13_CONN PULL_UP
#define SWITCH13_PIN PIN26

#define SWITCH14_CONN PULL_UP
#define SWITCH14_PIN PIN26

#define SWITCH15_CONN PULL_UP
#define SWITCH15_PIN PIN26

#define SWITCH16_CONN PULL_UP
#define SWITCH16_PIN PIN26

#define SWITCH17_CONN PULL_UP
#define SWITCH17_PIN PIN26

#define SWITCH18_CONN PULL_UP
#define SWITCH18_PIN PIN26

#define SWITCH19_CONN PULL_UP
#define SWITCH19_PIN PIN26

#define SWITCH20_CONN PULL_UP
#define SWITCH20_PIN PIN26

#define SWITCH21_CONN PULL_UP
#define SWITCH21_PIN PIN17

#define SWITCH22_CONN PULL_UP
#define SWITCH22_PIN PIN18

#define SWITCH23_CONN PULL_UP
#define SWITCH23_PIN PIN26

#define SWITCH24_CONN PULL_UP
#define SWITCH24_PIN PIN26

#define SWITCH25_CONN PULL_UP
#define SWITCH25_PIN PIN26

#define SWITCH26_CONN PULL_UP
#define SWITCH26_PIN PIN26

#define SWITCH27_CONN PULL_UP
#define SWITCH27_PIN PIN26

#define SWITCH28_CONN PULL_UP
#define SWITCH28_PIN PIN26

#define SWITCH29_CONN PULL_UP
#define SWITCH29_PIN PIN26

#define SWITCH30_CONN PULL_UP
#define SWITCH30_PIN PIN26

#define SWITCH31_CONN PULL_UP
#define SWITCH31_PIN PIN26

#endif /* SWITCH_DRIVER_SWITCH_CFG_H_ */
